const scores = {
  games: [
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 2,
            vegetables: 4,
            sheep: 3,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 3,
            sheep: 2,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": -1,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 12,
            "points for cards": 1,
            "bonus points": 2,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 3,
            vegetables: -1,
            sheep: 2,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 2,
          },
        },
      ],
      date: "6/4/2016",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 2,
            vegetables: 2,
            sheep: 1,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 2,
            vegetables: 4,
            sheep: 4,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 8,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 2,
            sheep: 2,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -2,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 7,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 12,
            "points for cards": 2,
            "bonus points": 1,
          },
        },
      ],
      date: "unknown",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 2,
            vegetables: 2,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Asia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 3,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -3,
            "fenced stables": 1,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 5,
            "bonus points": 7,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 3,
            sheep: 1,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: -1,
            sheep: -1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 7,
            "bonus points": 3,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 2,
            pastures: 4,
            grain: 2,
            vegetables: 1,
            sheep: 2,
            "wild boar": 2,
            cattle: 4,
            "unused spaces": -3,
            "fenced stables": 1,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 3,
          },
        },
        {
          name: "Rob",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 2,
            sheep: 3,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 12,
            "points for cards": 2,
            "bonus points": 2,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: -1,
            sheep: 1,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 3,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 4,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 2,
            vegetables: 2,
            sheep: 1,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 9,
            "points for cards": 3,
            "bonus points": 1,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 4,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 3,
            vegetables: -1,
            sheep: -1,
            "wild boar": 3,
            cattle: -1,
            "unused spaces": -2,
            "fenced stables": 1,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 6,
            "points for cards": 3,
            "bonus points": 5,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 2,
            grain: 1,
            vegetables: 1,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -6,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 14,
            "bonus points": 0,
          },
        },
        {
          name: "James",
          scores: {
            fields: -1,
            pastures: 2,
            grain: -1,
            vegetables: -1,
            sheep: 4,
            "wild boar": 4,
            cattle: 2,
            "unused spaces": -7,
            "fenced stables": 2,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 6,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
        {
          name: "Jonny",
          scores: {
            fields: 0,
            pastures: 5,
            grain: 4,
            vegetables: 1,
            sheep: -1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "CJ & Jeff",
          scores: {
            fields: 2,
            pastures: 2,
            grain: -1,
            vegetables: -1,
            sheep: 4,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": -4,
            "fenced stables": 2,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 1,
            grain: 4,
            vegetables: 1,
            sheep: 2,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 12,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 2,
            sheep: 2,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 9,
            "points for cards": 3,
            "bonus points": 1,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 1,
            pastures: 4,
            grain: 4,
            vegetables: -1,
            sheep: 4,
            "wild boar": 2,
            cattle: 4,
            "unused spaces": -6,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 4,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: -1,
            pastures: 4,
            grain: 1,
            vegetables: -1,
            sheep: 4,
            "wild boar": -1,
            cattle: 2,
            "unused spaces": -7,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 4,
            "family members": 6,
            "points for cards": 6,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 3,
            sheep: 2,
            "wild boar": 3,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 3,
            "wild boar": 0,
            cattle: 0,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 2,
            grain: 4,
            vegetables: 0,
            sheep: 2,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Rob",
          scores: {
            fields: 2,
            pastures: 1,
            grain: 1,
            vegetables: 0,
            sheep: 0,
            "wild boar": 0,
            cattle: 4,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 9,
            "points for cards": 0,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Jeff",
          scores: {
            fields: -1,
            pastures: 2,
            grain: -1,
            vegetables: -1,
            sheep: 4,
            "wild boar": -1,
            cattle: 3,
            "unused spaces": -4,
            "fenced stables": 3,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 12,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 3,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 2,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 1,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Jonny",
          scores: {
            fields: 2,
            pastures: 1,
            grain: 1,
            vegetables: 4,
            sheep: 2,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -5,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Jonny",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 1,
            vegetables: 3,
            sheep: 2,
            "wild boar": 4,
            cattle: 4,
            "unused spaces": -4,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "James",
          scores: {
            fields: 1,
            pastures: 2,
            grain: 1,
            vegetables: 2,
            sheep: 2,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 12,
            "points for cards": 4,
            "bonus points": 7,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Jonny",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 1,
            vegetables: 3,
            sheep: 2,
            "wild boar": 4,
            cattle: 4,
            "unused spaces": -4,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "James",
          scores: {
            fields: 1,
            pastures: 2,
            grain: 1,
            vegetables: 2,
            sheep: 2,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 12,
            "points for cards": 4,
            "bonus points": 7,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 1,
            pastures: 3,
            grain: -1,
            vegetables: -1,
            sheep: 1,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -6,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
        {
          name: "James",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Tom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 2,
            sheep: 2,
            "wild boar": -1,
            cattle: 3,
            "unused spaces": -3,
            "fenced stables": 1,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 6,
            "points for cards": 1,
            "bonus points": 4,
          },
        },
        {
          name: "CJ & Jeff",
          scores: {
            fields: 2,
            pastures: 4,
            grain: 1,
            vegetables: 2,
            sheep: 4,
            "wild boar": 3,
            cattle: 1,
            "unused spaces": -3,
            "fenced stables": 3,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 12,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: -1,
            grain: 4,
            vegetables: 3,
            sheep: -1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 7,
          },
        },
      ],
      date: "10/01/2016",
      location: "UK",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 3,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 3,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: -1,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 4,
            "wild boar": 4,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 6,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 1,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 4,
            sheep: -1,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 2,
            vegetables: 3,
            sheep: 4,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 1,
            vegetables: 3,
            sheep: 1,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 14,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 1,
            vegetables: 3,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 4,
            cattle: 4,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 2,
            grain: 1,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 4,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 5,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -3,
            "fenced stables": 4,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 1,
            "wild boar": 1,
            cattle: 2,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 2,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 3,
            vegetables: 2,
            sheep: 2,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": -5,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 5,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 2,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 2,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 2,
            sheep: -1,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 0,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 1,
            pastures: 2,
            grain: -1,
            vegetables: 4,
            sheep: 4,
            "wild boar": 3,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 4,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 4,
            sheep: -1,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 0,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 4,
            sheep: 4,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 3,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 3,
            vegetables: 4,
            sheep: -1,
            "wild boar": -1,
            cattle: 3,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 10,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: -1,
            vegetables: 4,
            sheep: 2,
            "wild boar": 4,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 2,
            vegetables: 3,
            sheep: -1,
            "wild boar": -1,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 3,
            sheep: 2,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: -1,
            pastures: 2,
            grain: -1,
            vegetables: 1,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 8,
            "bonus points": -3,
          },
        },
        {
          name: "James",
          scores: {
            fields: 1,
            pastures: 3,
            grain: 1,
            vegetables: 1,
            sheep: 2,
            "wild boar": 2,
            cattle: 4,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 1,
            "bonus points": 3,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 1,
            grain: -1,
            vegetables: -1,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -3,
            "fenced stables": 1,
            "clay rooms": 6,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 3,
            vegetables: 3,
            sheep: 1,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 2,
          },
        },
        {
          name: "James",
          scores: {
            fields: 2,
            pastures: 4,
            grain: -1,
            vegetables: -1,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -3,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 3,
            vegetables: 4,
            sheep: 2,
            "wild boar": -1,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 3,
          },
        },
        {
          name: "James",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 1,
            vegetables: 1,
            sheep: 1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 2,
            vegetables: 4,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 2,
          },
        },
      ],
      date: "unknown",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 1,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "James",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 4,
            grain: 1,
            vegetables: 1,
            sheep: -1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 4,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
      ],
      date: "22/12/18",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 1,
          },
        },
      ],
      date: "28/5/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 2,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 6,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
      ],
      date: "30/06/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 4,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 5,
          },
        },
      ],
      date: "1/07/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 2,
            vegetables: 3,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 15,
            "points for cards": 10,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 1,
            vegetables: 3,
            sheep: 2,
            "wild boar": -1,
            cattle: 4,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": -3,
            "bonus points": 6,
          },
        },
      ],
      date: "14/07/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 1,
            grain: 2,
            vegetables: 3,
            sheep: 1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": -4,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 2,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 3,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 10,
            "bonus points": 0,
          },
        },
      ],
      date: "18/08/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 2,
            vegetables: 2,
            sheep: 1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 3,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 3,
            vegetables: 2,
            sheep: -1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 11,
          },
        },
      ],
      date: "unknown",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 2,
            vegetables: 3,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 4,
          },
        },
        {
          name: "James",
          scores: {
            fields: -1,
            pastures: 2,
            grain: -1,
            vegetables: 1,
            sheep: 1,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": -5,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 12,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: -1,
            "wild boar": 3,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "18/05/2019",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 2,
            vegetables: 3,
            sheep: 2,
            "wild boar": 2,
            cattle: 4,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 2,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 8,
          },
        },
      ],
      date: "6/06/2019",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 2,
            grain: 4,
            vegetables: 3,
            sheep: 1,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 2,
            pastures: 2,
            grain: 1,
            vegetables: 2,
            sheep: -1,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 10,
          },
        },
      ],
      date: "18/02/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 1,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 2,
            "wild boar": 3,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: -1,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 10,
            "bonus points": 3,
          },
        },
      ],
      date: "24/02/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 2,
            vegetables: 4,
            sheep: 3,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 3,
            cattle: 4,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
      ],
      date: "21/05/2018",
      location: "Malaysia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 4,
            grain: -1,
            vegetables: 4,
            sheep: -1,
            "wild boar": 3,
            cattle: 4,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": 2,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 2,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 1,
            pastures: 3,
            grain: 1,
            vegetables: 2,
            sheep: 2,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": -3,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 7,
          },
        },
      ],
      date: "17/12/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 2,
            vegetables: 2,
            sheep: 1,
            "wild boar": 1,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 0,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 3,
            sheep: -1,
            "wild boar": 1,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 7,
          },
        },
      ],
      date: "23/12/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: -1,
            pastures: 3,
            grain: -1,
            vegetables: 1,
            sheep: 2,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -3,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 6,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 4,
            cattle: -1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 5,
          },
        },
      ],
      date: "30/12/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 4,
            vegetables: 4,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 20,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 3,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 2,
            vegetables: 4,
            sheep: 4,
            "wild boar": 4,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 3,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 6,
            "bonus points": 7,
          },
        },
      ],
      date: "1/01/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 2,
            grain: -1,
            vegetables: 2,
            sheep: -1,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 4,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 3,
            "clay rooms": 6,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "20/01/2018",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 4,
            vegetables: 4,
            sheep: 4,
            "wild boar": 2,
            cattle: 0,
            "unused spaces": 0,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 4,
            vegetables: -1,
            sheep: -1,
            "wild boar": 3,
            cattle: 0,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 6,
          },
        },
      ],
      date: "30/10/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 1,
            pastures: 2,
            grain: 1,
            vegetables: 2,
            sheep: 2,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 8,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 1,
            vegetables: 4,
            sheep: 2,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 11,
            "bonus points": 3,
          },
        },
      ],
      date: "3/11/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 1,
            grain: -1,
            vegetables: -1,
            sheep: -1,
            "wild boar": -1,
            cattle: -1,
            "unused spaces": -4,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 12,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: -1,
            pastures: 2,
            grain: -1,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -6,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 0,
          },
        },
      ],
      date: "15/11/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 1,
            vegetables: 4,
            sheep: 2,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 1,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 4,
            grain: 4,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
      ],
      date: "30/11/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 2,
            vegetables: 4,
            sheep: 2,
            "wild boar": -1,
            cattle: 1,
            "unused spaces": -2,
            "fenced stables": 2,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 9,
            "points for cards": 6,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 3,
            grain: 2,
            vegetables: 4,
            sheep: 2,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 3,
          },
        },
      ],
      date: "29/09/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 2,
            pastures: 3,
            grain: 1,
            vegetables: 4,
            sheep: 4,
            "wild boar": 3,
            cattle: 3,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 5,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 3,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 4,
            sheep: 3,
            "wild boar": -1,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 7,
            "bonus points": 0,
          },
        },
      ],
      date: "unknown",
      location: "unknown",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: 4,
            sheep: 2,
            "wild boar": 2,
            cattle: 3,
            "unused spaces": -2,
            "fenced stables": 1,
            "clay rooms": 4,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 4,
            "bonus points": 2,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 4,
            grain: 4,
            vegetables: 2,
            sheep: 4,
            "wild boar": 2,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 1,
          },
        },
      ],
      date: "20/10/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 1,
            sheep: -1,
            "wild boar": 1,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 5,
            "bonus points": 3,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 3,
            vegetables: 4,
            sheep: 1,
            "wild boar": 2,
            cattle: 1,
            "unused spaces": 0,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 0,
          },
        },
      ],
      date: "22/10/2017",
      location: "Australia",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 3,
            grain: 1,
            vegetables: 3,
            sheep: -1,
            "wild boar": 4,
            cattle: 1,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 11,
            "bonus points": 3,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 4,
            vegetables: 4,
            sheep: 1,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": 0,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 12,
            "family members": 15,
            "points for cards": 1,
            "bonus points": 2,
          },
        },
      ],
      date: "15/09/2019",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 3,
            vegetables: 4,
            sheep: 4,
            "wild boar": 1,
            cattle: -1,
            "unused spaces": -2,
            "fenced stables": 1,
            "clay rooms": 0,
            "stone rooms": 0,
            "family members": 15,
            "points for cards": 8,
            "bonus points": 15,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 2,
            grain: 3,
            vegetables: 4,
            sheep: -1,
            "wild boar": -1,
            cattle: 3,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 8,
            "family members": 15,
            "points for cards": 9,
            "bonus points": 2,
          },
        },
      ],
      date: "12/10/2019",
      location: "UK",
    },
    {
      players: [
        {
          name: "Tash",
          scores: {
            fields: 3,
            pastures: 2,
            grain: 3,
            vegetables: 3,
            sheep: 1,
            "wild boar": 3,
            cattle: 2,
            "unused spaces": -1,
            "fenced stables": 0,
            "clay rooms": 0,
            "stone rooms": 10,
            "family members": 15,
            "points for cards": 2,
            "bonus points": 0,
          },
        },
        {
          name: "Thom",
          scores: {
            fields: 4,
            pastures: 1,
            grain: 1,
            vegetables: 4,
            sheep: -1,
            "wild boar": 1,
            cattle: 3,
            "unused spaces": -2,
            "fenced stables": 0,
            "clay rooms": 4,
            "stone rooms": 15,
            "family members": 10,
            "points for cards": 4,
            "bonus points": 0,
          },
        },
      ],
      date: "30/11/2019",
      location: "UK",
    },
  ],
};
const util = require("util");
const fs = require("fs");

const convertedCats = scores.games.map((game) => {
  game.players.map((player) => {
    const catScores = Object.entries(player.scores).reduce(
      (acc, [key, value]) => {
        acc.push({ category: key, value: value });
        return acc;
      },
      []
    );
    const totalScore = Object.values(player.scores).reduce(
      (acc, val) => (acc += val)
    );
    player.scores = catScores;
    player.scores.push({ category: "total", value: totalScore });

    return player;
  });
  return game;
});

console.log(util.inspect(convertedCats, false, null, true /* enable colors */));
fs.writeFileSync(
  "formattedScores.json",
  JSON.stringify({ games: convertedCats })
);
